basic react framework
charlesma11/comp523-swayambhu pull request #4
Opened 2023-10-12 17:58 UTC by jessikka12

without the annotations

2023-10-12 19:27 UTC, charlesma11 requested changes

2023-10-12 19:27 UTC, charlesma11 commented on src/Annotation.js
> +import * as React from 'react';
Lets put these files into a folder called `components`

2023-10-12 19:27 UTC, charlesma11 commented on src/AnnotationList.js
> +          embedId='vvN4FgqNXwE'
what is this?

2023-10-12 19:27 UTC, charlesma11 commented on src/App.js
> +  const [tutOpen, setTutOpen] = useState(true);
lets rename these states to something like `tutorialIsOpen`

2023-10-12 19:27 UTC, charlesma11 commented on src/App.js
> +  const [tutOpen, setTutOpen] = useState(true);
length is not as important as good naming

2023-10-12 19:27 UTC, charlesma11 commented on src/Tutorial.js
> +        <Dialog
Reason for using Dialog here over Typography?

2023-10-12 19:27 UTC, charlesma11 commented on src/YoutubEmbed.js
> +const YoutubeEmbed = ({ embedId }) => (
we can stick with this for now, will just need Lauren to upload vids as youtube links

2023-10-12 19:27 UTC, charlesma11 commented on src/App.css
> +  height: 7vh;
y vh over px?

2023-10-12 19:29 UTC, charlesma11 commented on src/Annotation.js
> +import * as React from 'react';
so the `Annotation.js`, `AnnotationList.js`, etc. all the components

2023-10-12 19:30 UTC, jessikka12 commented on src/Tutorial.js
> +        <Dialog
dialog is the thing that pops up over the screen. typography is just a fancy text field

2023-10-12 19:32 UTC, jessikka12 commented on src/App.css
> +  height: 7vh;
vh let's u do a percentage of the screens height. for different sized devices

2023-10-12 19:33 UTC, jessikka12 commented on src/App.js
> +  const [tutOpen, setTutOpen] = useState(true);
sure

2023-10-12 19:33 UTC, jessikka12 commented on src/Annotation.js
> +import * as React from 'react';
sure

2023-10-12 19:46 UTC, jessikka12 commented on src/AnnotationList.js
> +          embedId='vvN4FgqNXwE'
the embedId?? that's the identifier for the video, it's the part in the youtube url link after "https://www.youtube.com/watch?v="

2023-10-23 15:44 UTC, charlesma11 approved these changes
lgtm

2023-10-24 14:34 UTC, merged